### ISSUE TITLE
Online Preview should enforce HTTPS

### ISSUE THREAD

**Issue by wafer-li** [Vonng/DDIA#138]
It is 2021 now, the [preview site](http://ddia.vonng.com/#/) should enforce HTTPS to gain better security.

If you use GitHub Pages to host the site, it should be a *Enforce HTTPS* checkbox to allow you enforce HTTPS

> Tested by Microsoft Edge 94.0.992.47

**Comment by Vonng** [comment]
That's very reasonable. 

The Github Page Link https://vonng.github.io/ddia/#/ is SSL enforced
While the preview site on private VPS both accept http & https for historic reason.

* http://ddia.vonng.com
* https://ddia.vonng.com

I've left some http:// links somewhere else. Have to keep it intact, so, sorry.
But it will do no harm since it's a static read-only site.

Still, thanks for your issue~
